name: ARCHSQL

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v1
       
   
        - uses: actions/upload-artifact@v2
          with:
             name: AzureSQLDB
             path: ${{ github.workspace }}\Database5.dacpac
        
    release:
        needs: build
        runs-on: windows-latest
        steps:
        - name: download AzureSQLDB artifact
          uses: actions/download-artifact@v2.0.6
          with:
             name: AzureSQLDB
        - name: AzureSQLDB
          uses: azure/login@v1
          with:
             creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: Azure SQL Deploy  
          uses: Azure/sql-action@v1
          with:
            server-name: 'kotthaserver.database.windows.net' 
            connection-string: '${{ secrets.AZURE_SQL_CONNECTION_STRING }}'
            dacpac-package: 'Database5.dacpac'
            arguments: '/p:AllowIncompatiblePlatform=true'

