on:
  push:
     branches: [ QA ]
  pull_request:
     branches: [ QA ]
    
    
jobs:
   build:
    runs-on: windows-latest
    steps:
     - uses: actions/checkout@v1
     - uses: azure/login@v1
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
        
     - uses: azure/sql-action@v1
       with:
        server-name: 'testdbserver.database.windows.net'
        connection-string: '${{ secrets.AZURE_SQL_CONNECTION_STRING }}'
        sql-file: './test_sql_script.sql'
        
        
     - name: array
       id: arr
       run: |
          arr=(i)
          for i in "$('./*.sql')"
          do
           
              arr+=($i)
          
          done
          echo ::set-output name=arr::${arr[@]}
        
     # Azure logout 
     - name: logout
       run: |
            az logout
